### ISSUE TITLE
Possible to add /opt folder to the LibreELEC image? 

### ISSUE THREAD

**Issue by brucezyc** [hanwckf/build-beikeyun#1]
Tried to install entware in LibreELEC and apparenly the ro system was not letting me create this folder. Is it possible to have this folder in the build?

**Comment by hanwckf** [comment]
Updated in https://github.com/hanwckf/build-beikeyun/commit/4de16c7bd8ff766bf87a1f0ad8cb936315d4e49c , you can try the latest release.

**Comment by brucezyc** [comment]
Thank you so much! I can see /opt with new version. Let me try it out and will reply here if anything!
