### ISSUE TITLE
PKGBUILD for beikeyun p1

### ISSUE THREAD

**Issue by Izumiko** [hanwckf/build-beikeyun#4]
H大，打扰一下。我尝试给Archlinux写了uboot、firmware还有linux-image的PKGBUILD。能否用这三个包和rootfs来生成镜像？这样不依赖armbian镜像，而且后续升级内核也方便些。

[Izumiko/PKGBUILD-beikeyun](https://github.com/Izumiko/PKGBUILD-beikeyun)

**Comment by hanwckf** [comment]
好，我有空再看看
